swagger: '2.0'
info:
  title: API Gateway Routing
  description: Gateway para redirigir a APIs en App Engine
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json

x-google-endpoints:
- name: "api-chepita-ishj3mvxxe5lh.apigateway.upn-homework-chepita.cloud.goog"
  allowCors: true

paths:
  /auth/**:
    options:
      summary: Soporte CORS preflight
      operationId: corsAuthOptions
      x-google-backend:
        address: https://auth-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '204':
          description: Respuesta CORS exitosa
    get:
      summary: Redirige a API 1
      operationId: api1GetAuth
      x-google-backend:
        address: https://auth-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '200':
          description: Respuesta exitosa
    post:
      summary: Redirige a API 1
      operationId: api1PostAuth
      x-google-backend:
        address: https://auth-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '200':
          description: Respuesta exitosa
    put:
      summary: Redirige a API 1
      operationId: api1PutAuth
      x-google-backend:
        address: https://auth-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '200':
          description: Respuesta exitosa
    delete:
      summary: Redirige a API 1
      operationId: api1DeleteAuth
      x-google-backend:
        address: https://auth-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '200':
          description: Respuesta exitosa

  /core/**:
    options:
      summary: Soporte CORS preflight
      operationId: corsCoreOptions
      x-google-backend:
        address: https://core-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '204':
          description: Respuesta CORS exitosa
    get:
      summary: Redirige a API 1
      operationId: api1GetCore
      x-google-backend:
        address: https://core-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '200':
          description: Respuesta exitosa
    post:
      summary: Redirige a API 1
      operationId: api1PostCore
      x-google-backend:
        address: https://core-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '200':
          description: Respuesta exitosa
    put:
      summary: Redirige a API 1
      operationId: api1PutCore
      x-google-backend:
        address: https://core-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '200':
          description: Respuesta exitosa
    delete:
      summary: Redirige a API 1
      operationId: api1DeleteCore
      x-google-backend:
        address: https://core-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '200':
          description: Respuesta exitosa

  /analytics/**:
    options:
      summary: Soporte CORS preflight
      operationId: corsAnalyticsOptions
      x-google-backend:
        address: https://analytics-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '204':
          description: Respuesta CORS exitosa
    get:
      summary: Redirige a API 1
      operationId: api1GetAnalytics
      x-google-backend:
        address: https://analytics-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '200':
          description: Respuesta exitosa
    post:
      summary: Redirige a API 1
      operationId: api1PostAnalytics
      x-google-backend:
        address: https://analytics-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '200':
          description: Respuesta exitosa
    put:
      summary: Redirige a API 1
      operationId: api1PutAnalytics
      x-google-backend:
        address: https://analytics-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '200':
          description: Respuesta exitosa
    delete:
      summary: Redirige a API 1
      operationId: api1DeleteAnalytics
      x-google-backend:
        address: https://analytics-service-dot-upn-homework-chepita.uc.r.appspot.com/
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
      responses:
        '200':
          description: Respuesta exitosa